### ISSUE TITLE
Dropdown issue on navbar

### ISSUE THREAD

**Issue by AllanSokolov** [AllanSokolov/clothing-webshop#1]
Dropdown menu doesn't work on desktop but on medium and small screen it shows the content.
![image](https://user-images.githubusercontent.com/16266791/132263077-db5f1884-0a57-408b-99ce-ed468d186b27.png)
![image](https://user-images.githubusercontent.com/16266791/132263170-9d4c55c9-b581-4686-84f8-b728ab56bd7c.png)

**Comment by samarth2727** [comment]
hey..! I would love to solve the bug. can you please assign the issue to me also?

**Comment by AllanSokolov** [comment]
Hi, if you solved the issue could you explain how you did it?

**Comment by GaborTeichter** [comment]
![image](https://user-images.githubusercontent.com/66086127/132962318-de6eb034-ced5-47e0-824e-2264bfe1d7ac.png)

Positioning the icons to the right side of the navbar.
