### ISSUE TITLE
Background image error on mobile view

### ISSUE THREAD

**Issue by AllanSokolov** [AllanSokolov/clothing-webshop#9]
The background image doesn't display on mobile view.

![image](https://user-images.githubusercontent.com/16266791/132750350-6134d514-687c-4c71-acdc-a43e9034c725.png)

**Comment by GaborTeichter** [comment]
I fixed it with media query.

![image](https://user-images.githubusercontent.com/66086127/132950056-c597730b-221e-4a97-893f-ee64cd8e6624.png)
